from __future__ import annotations

from dataclasses import dataclass, field
import fnmatch
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Set, Tuple
import re

from privacyprov.core.graph import ProvenanceGraph, Node
from .models import PrivacyConfig
from .ontology import PrivacyOntology
from .operation_policy import OperationPolicyConfig, OperationPolicySpec


ARTIFACT_LABELS = {
    "DatasetArtifact",
    "DataRecordArtifact",
    "DataCellArtifact",
    "ModelArtifact",
    "EvaluationMetric",
    "Artifact",
}


def _unique(values: Iterable[str]) -> List[str]:
    return list(dict.fromkeys(str(v) for v in values if v is not None and str(v) != ""))


def _safe_key(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_:\-.]+", "_", text)


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y"}
    return bool(value)


@dataclass
class PrivacyFacets: # the main privacy facets
    """Concrete C/U/R/A value used internally by the propagation engine."""

    C: List[str] = field(default_factory=list) # the full category set after applyign ontogoloy implications
    C_explicit: List[str] = field(default_factory=list) # means the categiries directly assigned on inferred by a rule.
    U: List[str] = field(default_factory=list)
    R: List[str] = field(default_factory=list)
    A: List[str] = field(default_factory=list)

    def copy(self) -> "PrivacyFacets":
        return PrivacyFacets(
            C=list(self.C),
            C_explicit=list(self.C_explicit),
            U=list(self.U),
            R=list(self.R),
            A=list(self.A),
        )

    def as_props(self) -> Dict[str, List[str]]:
        return {
            "C": _unique(self.C),
            "C_explicit": _unique(self.C_explicit),
            "U": _unique(self.U),
            "R": _unique(self.R),
            "A": _unique(self.A),
        }


class PrivacyPropagationEngine:
    """Operator-aware privacy propagation over the instrumented provenance graph.

    The engine consumes three inputs:
    - the provenance graph generated by the workflow instrumentation layer;
    - the manually supplied initial privacy configuration;
    - the operation policy dictionary.

    It produces propagated PrivacyAnnotation nodes and materialised C/U/R/A
    properties on output DatasetArtifact, DataRecordArtifact, DataCellArtifact,
    and ModelArtifact nodes.
    """

    def __init__(
        self,
        graph: ProvenanceGraph,
        privacy_config: PrivacyConfig,
        operation_policy_config: OperationPolicyConfig,
    ) -> None:
        self.graph = graph
        self.privacy_config = privacy_config
        self.operation_policy_config = operation_policy_config
        self.ontology = PrivacyOntology(privacy_config.category_implications)
        self.annotation_counter = self._initial_annotation_counter()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def apply(self) -> Dict[str, Any]: # it loops over all StepRun nodes in execution order. For each step run, it finds the attached operation policy
        """Run privacy propagation for all StepRuns with operation policies."""
        summary: Dict[str, Any] = {
            "step_runs_processed": 0,
            "annotations_created": 0,
            "cell_annotations_created": 0,
            "record_annotations_created": 0,
            "dataset_annotations_created": 0,
            "model_annotations_created": 0,
            "skipped_step_runs": [],
        }

        for step_run in self._step_runs_in_order():
            policy_id = step_run.props.get("operation_policy_id") or step_run.props.get("policy_id")
            if not policy_id:
                summary["skipped_step_runs"].append({"step_run": step_run.key, "reason": "missing_policy_id"})
                continue
            policy = self.operation_policy_config.operation_policies.get(str(policy_id))
            if policy is None:
                summary["skipped_step_runs"].append({"step_run": step_run.key, "reason": f"policy_not_found:{policy_id}"})
                continue

            op = policy.operatorType.upper()
            before = self._count_privacy_annotations()
            if op == "TR":
                self._propagate_tr(step_run, policy)
            elif op == "RED":
                self._propagate_red(step_run, policy)
            elif op == "FUS":
                self._propagate_fus(step_run, policy)
            elif op == "LEARN":
                self._propagate_learn(step_run, policy)
            elif op == "AGG":
                self._propagate_agg(step_run, policy)
            else:
                # Conservative fallback: artifact-level propagation from all used inputs.
                self._propagate_generic(step_run, policy)
            after = self._count_privacy_annotations()
            created = after - before
            summary["annotations_created"] += created
            summary["step_runs_processed"] += 1

        # Recount by target label/source to avoid overpromising from per-step counts.
        source_counts = self._propagated_annotation_counts()
        summary.update(source_counts)
        summary["cell_annotations_created"] = source_counts.get("propagated_DataCellArtifact_annotations", 0)
        summary["record_annotations_created"] = source_counts.get("propagated_DataRecordArtifact_annotations", 0)
        summary["dataset_annotations_created"] = source_counts.get("propagated_DatasetArtifact_annotations", 0)
        summary["model_annotations_created"] = source_counts.get("propagated_ModelArtifact_annotations", 0)
        return summary

    def artifact_privacy_summary(self, artifact_ids: Sequence[str]) -> Dict[str, Dict[str, Any]]:
        """Return C/U/R/A materialised on selected artifact IDs."""
        result: Dict[str, Dict[str, Any]] = {}
        for artifact_id in artifact_ids:
            node = self._find_artifact(artifact_id)
            if node is None:
                result[artifact_id] = {"missing": True}
                continue
            result[artifact_id] = {
                "label": node.label,
                "C": node.props.get("privacy_categories", []),
                "C_explicit": node.props.get("privacy_categories_explicit", []),
                "U": node.props.get("privacy_usages", []),
                "R": node.props.get("privacy_erasures", []),
                "A": node.props.get("privacy_roles", []),
                "sources": node.props.get("privacy_annotation_sources", []),
            }
        return result

    # ------------------------------------------------------------------
    # Operator-specific propagation
    # ------------------------------------------------------------------
    def _propagate_tr(self, step_run: Node, policy: OperationPolicySpec) -> None:
        """Transformations: preserve or rewrite cell-level categories by rule.

        For the ASD normalisation example, this maps HR_res -> HR_norm,
        EDA_res -> EDA_norm, ACC_res -> ACC_norm, and copies unchanged columns.
        Dataset-level risks such as reidentification_risk are preserved for the
        output dataset unless a later RED/projection policy removes them.
        """
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return

        # The current prototype handles the common one-input/one-output TR case.
        input_ds = inputs[0]
        output_ds = outputs[0]

        # Propagate cells using transformation rules.
        cell_count = 0
        if output_ds.label == "DatasetArtifact":
            for out_cell in self._cells_for_dataset(output_ds.key):
                out_attr = str(out_cell.props.get("attribute"))
                transform = policy.transformations.get(out_attr)
                if transform is None:
                    # Support wildcard transformation policies such as education_* -> education.
                    for pattern, spec in policy.transformations.items():
                        if fnmatch.fnmatch(out_attr, str(pattern)):
                            transform = spec
                            break
                if transform:
                    source_attrs = [str(a) for a in transform.get("derivedFrom", [])]
                else:
                    # Default for unchanged attributes: same-name source attribute.
                    source_attrs = [out_attr]
                source_cells = [
                    c for attr in source_attrs
                    for c in self._matching_input_cells(input_ds.key, out_cell, attr)
                ]
                if not source_cells:
                    continue
                facets = self._combine_nodes(source_cells)
                self._annotate_node(
                    out_cell,
                    facets,
                    source="propagated:TR",
                    granularity="cell",
                    generated_by=step_run,
                    policy=policy,
                    note=f"TR propagation for output attribute {out_attr}",
                )
                cell_count += 1

            # Record annotations from propagated output cells.
            self._annotate_records_from_cells(output_ds, step_run, policy, source="propagated:TR")

            # Dataset annotation: preserve input dataset-level annotation, then merge
            # cell-level derived annotations. This keeps dataset-level minted risks
            # such as reidentification_risk through ordinary transformations.
            input_dataset_facets = self._node_facets(input_ds)
            output_cell_facets = self._combine_nodes(self._cells_for_dataset(output_ds.key))
            facets = self._merge_facets(input_dataset_facets, output_cell_facets, intersect_permissions=False)
            # For TR, retain the stricter dataset roles/usages when they exist.
            if input_dataset_facets.U:
                facets.U = input_dataset_facets.U
            if input_dataset_facets.A:
                facets.A = input_dataset_facets.A
            self._annotate_node(
                output_ds,
                facets,
                source="propagated:TR",
                granularity="dataset",
                generated_by=step_run,
                policy=policy,
                note="TR dataset-level propagation preserving input dataset-level governance constraints.",
            )

    def _propagate_red(self, step_run: Node, policy: OperationPolicySpec) -> None:
        """Reduction/projection/split propagation.

        Projection policies with selectedAttributes are propagated from retained
        output cells only. Split policies are propagated by matching output
        records/cells back to input records/cells by record_id and attribute.
        """
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return
        input_ds = inputs[0]

        for output_ds in outputs:
            if output_ds.label != "DatasetArtifact":
                self._propagate_generic(step_run, policy)
                continue

            selected = set(policy.selectedAttributes or output_ds.props.get("columns", []))
            if not selected:
                selected = set(output_ds.props.get("columns", []))

            # Cell-level propagation by matching output record_id and attribute.
            for out_cell in self._cells_for_dataset(output_ds.key):
                attr = str(out_cell.props.get("attribute"))
                if selected and attr not in selected:
                    continue
                source_cells = self._matching_input_cells(input_ds.key, out_cell, attr)
                if not source_cells:
                    # Projection may rename columns. Fall back to same attribute lookup only.
                    continue
                facets = self._combine_nodes(source_cells)
                self._annotate_node(
                    out_cell,
                    facets,
                    source="propagated:RED",
                    granularity="cell",
                    generated_by=step_run,
                    policy=policy,
                    note=f"RED propagation for retained attribute {attr}",
                )

            self._annotate_records_from_cells(output_ds, step_run, policy, source="propagated:RED")

            # Dataset-level result from retained cells/records, not from the whole input dataset.
            cells = self._cells_for_dataset(output_ds.key)
            facets = self._combine_nodes(cells)
            facets = self._apply_risk_removal_rules(facets, policy)
            # Projection/split datasets should generally keep output dataset U/R/A
            # from retained contributors; no dataset-level policy is copied if the
            # removed attributes were responsible for stricter access.
            self._annotate_node(
                output_ds,
                facets,
                source="propagated:RED",
                granularity="dataset",
                generated_by=step_run,
                policy=policy,
                note="RED dataset-level propagation from retained contributors.",
            )

    def _propagate_fus(self, step_run: Node, policy: OperationPolicySpec) -> None:
        """Fusion/join propagation. Implemented conservatively at artifact level."""
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return
        base = self._combine_nodes(inputs)
        base = self._apply_minting_rules(base, policy, context_nodes=inputs)
        for output in outputs:
            self._annotate_node(
                output,
                base,
                source="propagated:FUS",
                granularity=self._granularity_for_label(output.label),
                generated_by=step_run,
                policy=policy,
                note="FUS propagation with operation-policy minting rules.",
            )

    def _propagate_agg(self, step_run: Node, policy: OperationPolicySpec) -> None:
        """Aggregation propagation. Conservative fallback with optional attenuation."""
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return
        facets = self._combine_nodes(inputs)
        facets = self._apply_attenuation_rules(facets, policy, inputs)
        for output in outputs:
            self._annotate_node(
                output,
                facets,
                source="propagated:AGG",
                granularity=self._granularity_for_label(output.label),
                generated_by=step_run,
                policy=policy,
                note="AGG propagation with operation-policy attenuation rules.",
            )

    def _propagate_learn(self, step_run: Node, policy: OperationPolicySpec) -> None:
        """Learning propagation: map training-data categories to model exposure."""
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return
        input_ds = inputs[0]

        # Select only the features and target used by the learning step.
        # A wildcard feature list means: all available attributes except explicitly
        # excluded attributes and the target label. This is useful for dataframe
        # pipelines with dynamic one-hot-encoded columns.
        excluded = set(str(a) for a in policy.excludedAttributes)
        if "*" in policy.features and input_ds.label == "DatasetArtifact":
            feature_attrs = sorted({
                str(cell.props.get("attribute"))
                for cell in self._cells_for_dataset(input_ds.key)
                if str(cell.props.get("attribute")) not in excluded
                and str(cell.props.get("attribute")) != str(policy.target)
            })
        else:
            feature_attrs = [str(a) for a in policy.features if str(a) not in excluded]
        used_attrs = _unique(feature_attrs + ([policy.target] if policy.target else []))
        contributor_cells: List[Node] = []
        if input_ds.label == "DatasetArtifact" and used_attrs:
            for cell in self._cells_for_dataset(input_ds.key):
                if str(cell.props.get("attribute")) in used_attrs:
                    contributor_cells.append(cell)
        if not contributor_cells:
            contributor_cells = self._cells_for_dataset(input_ds.key) if input_ds.label == "DatasetArtifact" else [input_ds]

        base = self._combine_nodes(contributor_cells)

        model_categories: List[str] = []
        explicit_categories = base.C_explicit or base.C
        for category in explicit_categories:
            mapped = policy.modelExposureMapping.get(category)
            if mapped:
                model_categories.append(mapped)

        # Some categories may only appear after implication closure, but the policy
        # may still intentionally map them. Add those mappings as well.
        for category in base.C:
            mapped = policy.modelExposureMapping.get(category)
            if mapped:
                model_categories.append(mapped)

        model_categories = _unique(model_categories)
        model_categories = self._apply_minting_rules(
            PrivacyFacets(C=model_categories, C_explicit=model_categories, U=base.U, R=base.R, A=base.A),
            policy,
            context_nodes=[input_ds],
        ).C_explicit

        erasures = self._rewrite_erasures(base.R, policy.erasureRewrite)
        roles = _unique(policy.modelAccessRoles or base.A)
        facets = PrivacyFacets(
            C=self.ontology.closure(model_categories),
            C_explicit=model_categories,
            U=base.U,
            R=erasures,
            A=roles,
        )

        for output in outputs:
            self._annotate_node(
                output,
                facets,
                source="propagated:LEARN",
                granularity="model" if output.label == "ModelArtifact" else self._granularity_for_label(output.label),
                generated_by=step_run,
                policy=policy,
                note="LEARN propagation using model-exposure category mapping.",
            )


    def _propagate_generic(self, step_run: Node, policy: OperationPolicySpec) -> None:
        inputs = self._input_artifacts(step_run, policy)
        outputs = self._output_artifacts(step_run, policy)
        if not inputs or not outputs:
            return
        facets = self._combine_nodes(inputs)
        for output in outputs:
            self._annotate_node(
                output,
                facets,
                source="propagated:GENERIC",
                granularity=self._granularity_for_label(output.label),
                generated_by=step_run,
                policy=policy,
                note="Generic artifact-level propagation fallback.",
            )

    # ------------------------------------------------------------------
    # Combination and policy transforms
    # ------------------------------------------------------------------
    def _node_facets(self, node: Node) -> PrivacyFacets:
        c = _unique(node.props.get("privacy_categories", []))
        explicit = _unique(node.props.get("privacy_categories_explicit", []) or c)
        return PrivacyFacets(
            C=c,
            C_explicit=explicit,
            U=_unique(node.props.get("privacy_usages", [])),
            R=_unique(node.props.get("privacy_erasures", [])),
            A=_unique(node.props.get("privacy_roles", [])),
        )

    def _combine_nodes(self, nodes: Iterable[Node]) -> PrivacyFacets:
        node_list = [n for n in nodes if n is not None]
        if not node_list:
            return PrivacyFacets()
        return self._combine_facets([self._node_facets(n) for n in node_list])

    def _combine_facets(self, facets_list: Sequence[PrivacyFacets]) -> PrivacyFacets:
        if not facets_list:
            return PrivacyFacets()

        categories: List[str] = []
        explicit_categories: List[str] = []
        erasures: List[str] = []
        usage_sets: List[Set[str]] = []
        role_sets: List[Set[str]] = []

        for facets in facets_list:
            categories.extend(facets.C)
            explicit_categories.extend(facets.C_explicit or facets.C)
            erasures.extend(facets.R)
            if facets.U:
                usage_sets.append(set(facets.U))
            if facets.A:
                role_sets.append(set(facets.A))

        usages = sorted(set.intersection(*usage_sets)) if usage_sets else []
        roles = sorted(set.intersection(*role_sets)) if role_sets else []
        explicit_categories = _unique(explicit_categories)
        closed = self.ontology.closure(_unique(categories or explicit_categories))
        return PrivacyFacets(
            C=closed,
            C_explicit=explicit_categories,
            U=_unique(usages),
            R=_unique(erasures),
            A=_unique(roles),
        )

    def _merge_facets(
        self,
        left: PrivacyFacets,
        right: PrivacyFacets,
        *,
        intersect_permissions: bool = True,
    ) -> PrivacyFacets:
        categories = _unique(left.C + right.C)
        explicit = _unique(left.C_explicit + right.C_explicit)
        erasures = _unique(left.R + right.R)
        if intersect_permissions:
            usages = _unique(sorted(set(left.U).intersection(right.U))) if left.U and right.U else _unique(left.U or right.U)
            roles = _unique(sorted(set(left.A).intersection(right.A))) if left.A and right.A else _unique(left.A or right.A)
        else:
            usages = _unique(left.U + right.U)
            roles = _unique(left.A + right.A)
        return PrivacyFacets(
            C=self.ontology.closure(categories),
            C_explicit=explicit,
            U=usages,
            R=erasures,
            A=roles,
        )

    def _apply_risk_removal_rules(self, facets: PrivacyFacets, policy: OperationPolicySpec) -> PrivacyFacets:
        updated = facets.copy()
        to_remove: Set[str] = set()
        for rule in policy.riskRemovalRules:
            to_remove.update(str(c) for c in rule.get("removeCategories", []) or rule.get("remove", []))
        if to_remove:
            updated.C_explicit = [c for c in updated.C_explicit if c not in to_remove]
            # Recompute closure from remaining explicit categories. This ensures
            # sensitive_personal_data may still appear if health/biometric remains.
            updated.C = self.ontology.closure(updated.C_explicit)
        return updated

    def _apply_minting_rules(
        self,
        facets: PrivacyFacets,
        policy: OperationPolicySpec,
        *,
        context_nodes: Sequence[Node],
    ) -> PrivacyFacets:
        updated = facets.copy()
        for rule in policy.mintingRules:
            condition = str(rule.get("condition", ""))
            should_apply = self._evaluate_minting_condition(condition, context_nodes)
            if should_apply:
                add = _unique(rule.get("addCategories", []) or rule.get("add", []))
                updated.C_explicit = _unique(updated.C_explicit + add)
                updated.C = self.ontology.closure(updated.C_explicit)
                restrict = _unique(rule.get("restrictRolesTo", []))
                if restrict:
                    if updated.A:
                        updated.A = _unique(sorted(set(updated.A).intersection(restrict)))
                    else:
                        updated.A = restrict
        return updated

    def _evaluate_minting_condition(self, condition: str, context_nodes: Sequence[Node]) -> bool:
        if not condition:
            return True
        condition = condition.strip().lower()
        if condition in {"always", "true"}:
            return True
        if condition == "training_set_size_less_than_10":
            for node in context_nodes:
                n_rows = node.props.get("n_rows")
                if isinstance(n_rows, int) and n_rows < 10:
                    return True
                try:
                    if n_rows is not None and int(n_rows) < 10:
                        return True
                except Exception:
                    pass
            return False
        if condition in {"join_on_identifier_or_quasi_identifier", "risk_causing_attributes_removed"}:
            # These are declarative conditions in the policy dictionary. The first
            # is assumed true when a FUS policy carries join keys; the second is
            # handled by risk-removal rules, not minting.
            return True
        return False

    def _apply_attenuation_rules(self, facets: PrivacyFacets, policy: OperationPolicySpec, contributors: Sequence[Node]) -> PrivacyFacets:
        updated = facets.copy()
        for rule in policy.attenuationRules:
            remove = _unique(rule.get("removeCategories", []) or rule.get("remove", []))
            if not remove:
                continue
            kmin = rule.get("kmin") or rule.get("threshold")
            if kmin is None:
                should_apply = True
            else:
                try:
                    should_apply = len(contributors) >= int(kmin)
                except Exception:
                    should_apply = False
            if should_apply:
                updated.C_explicit = [c for c in updated.C_explicit if c not in set(remove)]
                updated.C = self.ontology.closure(updated.C_explicit)
        return updated

    def _rewrite_erasures(self, erasures: Sequence[str], rewrite: Mapping[str, str]) -> List[str]:
        output: List[str] = []
        for obligation in erasures:
            if obligation in rewrite:
                output.append(str(rewrite[obligation]))
            else:
                output.append(str(obligation))
        return _unique(output)

    # ------------------------------------------------------------------
    # Annotation materialisation
    # ------------------------------------------------------------------
    def _annotate_records_from_cells(
        self,
        dataset_node: Node,
        step_run: Node,
        policy: OperationPolicySpec,
        *,
        source: str,
    ) -> None:
        for record in self._records_for_dataset(dataset_node.key):
            cells = self._cells_for_record(record.key)
            if not cells:
                continue
            facets = self._combine_nodes(cells)
            self._annotate_node(
                record,
                facets,
                source=source,
                granularity="record",
                generated_by=step_run,
                policy=policy,
                note=f"Record-level annotation summarised from cells of {dataset_node.key}.",
            )

    def _annotate_node(
        self,
        target: Node,
        facets: PrivacyFacets,
        *,
        source: str,
        granularity: str,
        generated_by: Optional[Node] = None,
        policy: Optional[OperationPolicySpec] = None,
        note: Optional[str] = None,
    ) -> Node:
        facets = facets.copy()
        facets.C_explicit = _unique(facets.C_explicit or facets.C)
        facets.C = self.ontology.closure(facets.C_explicit)
        facets.U = _unique(facets.U)
        facets.R = _unique(facets.R)
        facets.A = _unique(facets.A)

        self.annotation_counter += 1
        ann_key = _safe_key(f"PA::prop::{target.label}::{target.key}::{self.annotation_counter:05d}")
        ann = self.graph.get_or_create_node(
            "PrivacyAnnotation",
            ann_key,
            annotationId=ann_key,
            target_label=target.label,
            target_key=target.key,
            granularity=granularity,
            source=source,
            policy_id=policy.policy_id if policy else None,
            generated_by=generated_by.key if generated_by else None,
            note=note,
            C_explicit=facets.C_explicit,
            C=facets.C,
            U=facets.U,
            R=facets.R,
            A=facets.A,
        )
        self.graph.add_rel("annotates", "PrivacyAnnotation", ann.key, target.label, target.key)
        if generated_by is not None:
            self.graph.add_rel("generatedPrivacyAnnotation", "StepRun", generated_by.key, "PrivacyAnnotation", ann.key)
            self.graph.add_rel("wasGeneratedBy", "PrivacyAnnotation", ann.key, "StepRun", generated_by.key)
        if policy is not None:
            self.graph.add_rel("usedPolicy", "PrivacyAnnotation", ann.key, "OperationPolicy", policy.policy_id)

        for category in facets.C:
            self.graph.get_or_create_node("SensitivityCategory", category, name=category)
            self.graph.add_rel(
                "hasCategory",
                "PrivacyAnnotation", ann.key,
                "SensitivityCategory", category,
                explicit=category in facets.C_explicit,
            )
        for usage in facets.U:
            self.graph.get_or_create_node("UsageConstraint", usage, name=usage)
            self.graph.add_rel("hasUsage", "PrivacyAnnotation", ann.key, "UsageConstraint", usage)
        for erasure in facets.R:
            self.graph.get_or_create_node("ErasureConstraint", erasure, name=erasure)
            self.graph.add_rel("hasErasure", "PrivacyAnnotation", ann.key, "ErasureConstraint", erasure)
        for role in facets.A:
            self.graph.get_or_create_node("AccessRole", role, name=role)
            self.graph.add_rel("allowsRole", "PrivacyAnnotation", ann.key, "AccessRole", role)

        self._merge_privacy_props(target, facets, source)
        return ann

    def _merge_privacy_props(self, node: Node, facets: PrivacyFacets, source: str) -> None:
        props = node.props
        props["privacy_categories"] = _unique(props.get("privacy_categories", []) + facets.C)
        props["privacy_categories_explicit"] = _unique(props.get("privacy_categories_explicit", []) + facets.C_explicit)
        props["privacy_usages"] = _unique(props.get("privacy_usages", []) + facets.U)
        props["privacy_erasures"] = _unique(props.get("privacy_erasures", []) + facets.R)
        props["privacy_roles"] = _unique(props.get("privacy_roles", []) + facets.A)
        props["privacy_annotation_sources"] = _unique(props.get("privacy_annotation_sources", []) + [source])

    # ------------------------------------------------------------------
    # Graph navigation helpers
    # ------------------------------------------------------------------
    def _initial_annotation_counter(self) -> int:
        count = 0
        for node in self.graph.nodes.values():
            if node.label == "PrivacyAnnotation":
                count += 1
        return count

    def _count_privacy_annotations(self) -> int:
        return len([n for n in self.graph.nodes.values() if n.label == "PrivacyAnnotation"])

    def _propagated_annotation_counts(self) -> Dict[str, int]:
        total = 0
        by_target: Dict[str, int] = {}
        for node in self.graph.nodes.values():
            if node.label != "PrivacyAnnotation":
                continue
            source = str(node.props.get("source", ""))
            if not source.startswith("propagated"):
                continue
            total += 1
            label = str(node.props.get("target_label", "unknown"))
            by_target[f"propagated_{label}_annotations"] = by_target.get(f"propagated_{label}_annotations", 0) + 1
        by_target["propagated_annotations_total"] = total
        return by_target

    def _step_runs_in_order(self) -> List[Node]:
        step_runs = [n for n in self.graph.nodes.values() if n.label == "StepRun"]

        def order_key(node: Node) -> Tuple[int, str]:
            parts = node.key.split("::")
            for part in parts:
                if part.isdigit():
                    return (int(part), node.key)
            return (999999, node.key)

        return sorted(step_runs, key=order_key)

    def _input_artifacts(self, step_run: Node, policy: OperationPolicySpec) -> List[Node]:
        return self._artifacts_from_rel(step_run, "used", direction="out", fallback_ids=policy.inputArtifacts)

    def _output_artifacts(self, step_run: Node, policy: OperationPolicySpec) -> List[Node]:
        return self._artifacts_from_rel(step_run, "wasGeneratedBy", direction="in", fallback_ids=policy.outputArtifacts)

    def _artifacts_from_rel(
        self,
        step_run: Node,
        rel_type: str,
        *,
        direction: str,
        fallback_ids: Sequence[str],
    ) -> List[Node]:
        nodes: List[Node] = []
        for rel in self.graph.relationships:
            if rel.rel_type != rel_type:
                continue
            if direction == "out" and rel.start_label == "StepRun" and rel.start_key == step_run.key:
                node = self.graph.nodes.get((rel.end_label, rel.end_key))
                if node is not None and node.label in ARTIFACT_LABELS:
                    nodes.append(node)
            elif direction == "in" and rel.end_label == "StepRun" and rel.end_key == step_run.key:
                node = self.graph.nodes.get((rel.start_label, rel.start_key))
                if node is not None and node.label in ARTIFACT_LABELS:
                    nodes.append(node)
        if not nodes:
            for artifact_id in fallback_ids:
                node = self._find_artifact(artifact_id)
                if node is not None:
                    nodes.append(node)
        return nodes

    def _find_artifact(self, artifact_id: str) -> Optional[Node]:
        for label in ARTIFACT_LABELS:
            node = self.graph.nodes.get((label, str(artifact_id)))
            if node is not None:
                return node
        return None

    def _records_for_dataset(self, dataset_id: str) -> List[Node]:
        records: List[Node] = []
        for rel in self.graph.relationships:
            if rel.rel_type == "containsDR" and rel.start_label == "DatasetArtifact" and rel.start_key == dataset_id:
                node = self.graph.nodes.get((rel.end_label, rel.end_key))
                if node is not None:
                    records.append(node)
        return records

    def _cells_for_dataset(self, dataset_id: str) -> List[Node]:
        return [
            n for n in self.graph.nodes.values()
            if n.label == "DataCellArtifact" and n.props.get("dataset_id") == dataset_id
        ]

    def _cells_for_record(self, record_key: str) -> List[Node]:
        cells: List[Node] = []
        for rel in self.graph.relationships:
            if rel.rel_type == "containsRC" and rel.start_label == "DataRecordArtifact" and rel.start_key == record_key:
                node = self.graph.nodes.get((rel.end_label, rel.end_key))
                if node is not None:
                    cells.append(node)
        return cells

    def _matching_input_cells(self, input_dataset_id: str, out_cell: Node, source_attribute: str) -> List[Node]:
        record_id = str(out_cell.props.get("record_id"))
        candidate_key = f"{input_dataset_id}::record::{record_id}::cell::{source_attribute}"
        node = self.graph.nodes.get(("DataCellArtifact", candidate_key))
        if node is not None:
            return [node]
        # Fallback: search by dataset, record_id, and attribute in case key policy changes.
        matches: List[Node] = []
        for n in self.graph.nodes.values():
            if n.label != "DataCellArtifact":
                continue
            if (
                n.props.get("dataset_id") == input_dataset_id
                and str(n.props.get("record_id")) == record_id
                and str(n.props.get("attribute")) == str(source_attribute)
            ):
                matches.append(n)
        return matches

    def _granularity_for_label(self, label: str) -> str:
        return {
            "DatasetArtifact": "dataset",
            "DataRecordArtifact": "record",
            "DataCellArtifact": "cell",
            "ModelArtifact": "model",
            "EvaluationMetric": "metric",
        }.get(label, "artifact")
